testsLocation: test/ply
expectedLocation: test/ply/results/expected
actualLocation: test/ply/results/actual

requestFiles: '**/*.ply.yaml'
caseFiles: '**/*.ply.ts'

# don't run these directly (they're for use by cases)
skip: 'requests/movies-api.ply.yaml'

verbose: false

valuesFiles:
  - test/ply/values/global.json
  - test/ply/values/localhost.json

