testsLocation: test/ply
expectedLocation: test/ply/results/expected
actualLocation: test/ply/results/actual

requestFiles: '**/*.{ply,ply.yaml}'
caseFiles: '**/*.ply.ts'
flowFiles: '**/*.ply.flow'

skip: '{requests/movies-api.ply.yaml,flows/plain-text-id.ply.flow}'
# needs ply-movies branch
ignore: 'flows/plain-text-id.ply.flow'

verbose: false

valuesFiles:
  - test/ply/values/global.json
  - test/ply/values/localhost.json

outputFile: ply-results.json
